name: test-GPT Kernel Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v4

      - name: Install packages
        run: |
          sudo apt update
          sudo apt install -y \
            git bc bison flex \
            build-essential \
            clang llvm lld \
            gcc-aarch64-linux-gnu \
            gcc-arm-linux-gnueabi \
            libssl-dev \
            libelf-dev \
            libncurses-dev \
            ccache \
            curl \
            zip \
            unzip \
            python3 \
            device-tree-compiler

      - name: Clone Copilote
        run: |
          git clone --depth=1 \
            --branch test-sukisu \
            https://github.com/Albanel22/Copilote.git

      - name: Make Copilote scripts executable
        run: |
          chmod +x Copilote/build/*.sh

      - name: Run Copilote Build
        run: |
          cd Copilote
          ./build/run.sh

      - name: Upload artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: Copilote-Build
          path: |
            Copilote/ReSukiSU-AnyKernel3-kiev.zip
            Copilote/kernel_src/build.log
            Copilote/kernel_src/out/**/*
