name: Copilote Kernel Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v4

      - name: Install packages
        run: |
          sudo apt update
          sudo apt install -y \
            git bc bison flex \
            build-essential \
            clang llvm lld \
            gcc-aarch64-linux-gnu \
            gcc-arm-linux-gnueabi \
            libssl-dev \
            libelf-dev \
            libncurses-dev \
            ccache \
            curl \
            zip \
            unzip \
            python3 \
            device-tree-compiler

      - name: Make scripts executable
        run: chmod +x build/*.sh

      - name: Build kernel
        run: ./build/run.sh

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: Copilote-Build
          path: |
            ReSukiSU-AnyKernel3-kiev.zip
            kernel_src/build.log
            kernel_src/out/**/*
